sudo: required
services:
 - docker
 
before_install:
 - docker build -t fate7/docker-react -f Dockerfile.dev .

script:
 - docker run fate7/docker-react -e CI=true npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 access_key_id: "AKIAUNCPZOWSMQDMV5TA"
 secret_access_key: $aws_secret_access
 region: "eu-west-3"
 app: "docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-eu-west-3-302962537892"
 bucket_path: "docker"
 on:
    branch: master
  
  
