sudo: required
services:
 - docker
 
before_install:
 - docker build -t fate7/docker-react -f Dockerfile.dev .

script:
 - docker run fate7/docker-react -e CI=true npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 access_key_id: 
  secure: "I4ycogxTPqbkMTd1uRhGmU4lwy2C7vB95JoWX3GAfuSRxFfpPdamhmzsijQe1WiUoHEUWsKwiI4lGDWGH3R/QcJ+d6hmBFXf2wtwhuqdGP09/K2EQqGPJ0+gtvCebhxsCbJFIURUZB4hRWMYpYGE8aJKp/QCJx3+t3UtTldI3VJZ3BRBpN+C7igQsXOfBLlqtUixRXFxr61v2u9wjx4i7bMazOPZELPYDNIrSQX7S2E27sedItIClht/qmdE4nFZEmYSXHu1igqsTnLtw62Xg76liTnO3JXG7gmXSFkcDVq9c6bc5e3athe9yvpD/bUFPlTAVdwk722ZAKxEAjnabRf82/tRt8dx1l9irquhtDPUyIv2EShNQhbxWil0sGmf2A3vgPJvj2eXZoMfE3Cmt9aE3hKtxT8zFKGD/7/1lZCXrhs76g1BWgCcT4GnY8bB5xzZOeFe4JY9SsZgcVFLKcZfov41DPdAxlmvMGTRzju+swIzgFkr4op7apguU9Vs3kW+cqJsVIg3DUEqKrEMi0agjs0N8u6jte9PlIZkGMquHb2J9FkPQ4vnDJY7P7e6bKZJxktFvyUW8Iy4G8vJwj3XEj5HHRybNatlx8TnagwjbeD84guWUhwvnEXPMq890UDOv3Zw8K3/gHUkvvHyZJkWf9mDbgVHYN9/qAGQztg="
 secret_access_key:
  secure: "OYIfjpj/6x3GqJd85vkk7Tw28H50SPnVGOQFPg+wtWcJIjWWXkGUKRPtfhAOgRNCgwgdLNdKzj0PHKmhpdFhlbfXOn5C7MXsbhmP1WoC76xeHzyeL9nOGaXnHaPSh4iZsHPfx/ksmWxjKQR0Yy0ReI5xG/1l+4niDmZEVqmUP4x440mHaHl0b2KWsDJOZoTJsuq+88bNkrgP3znU1rypPWApLJIGVei69ghClXMmdXrtN7pxzVg6YMvckx0blxv/JApdOuuAhVafu1Alo3dT4rOSbUSFWUUBPrLeWcADlruBVfk+h3ZgXYv8tmYwhdqTIZZ5P7wBVoJhYtmCLpw8xafhhCFcluljZRSoNVxFFD2yk485XmLTEweujKz+GFgk0s9RrvB+R0vOGSok6r0pt7ZEJicyAndDLaIhPM/IFVscozACRUJNAoapWP50Bf9WYcim2f7UyINzbCAFo1nvo5+04IYR0wV8iLTbOlcPw3F0PASMy4GtBSAC32ZPVFy2VOgbegF7yrQp8JtrdfGRTqdq3QHpI4Kk18GY1NzT89lrS7rUlv/KukSB8RW8BP4e2b7BElJV4+GSi3W/QmfCEQfL8X/yScQYVCxmcmN3tFVo0Ham3CbRbPSup+TR+kkQ/PNVEqyfFq0Ztpcpm54n146M5DHEvlHeUt+etpatdco="
 region: "us-east-1"
 app: "Docker"
 env: "Docker-env"
 bucket_name: "elasticbeanstalk-us-east-1-302962537892"
  
  
